package com.project.vetdata.enums;

public enum ReasonHospitalization {
    POS_OPERATORIO, GASTROENTEROLOGIA, DERMATOLOGIA, ONCOLOGIA, ORTOPEDIA_E_TRAUMATOLOGIA, NEFROLOGIA, NEUROLOGIA, OFTALMOLOGIA, HEMATOLOGIA, OUTROS, UROLOGIA,
    PNEUMOLOGIA, ENDOCRINOLOGIA
}
