package com.project.vetdata.enums;

public enum TreatmentNextSteps {
    TRATAMENTO_EM_ANDAMENTO, ENCAMINHAMENTO_ESPECIALISTA, ENCAMINHAMENTO_HOVET_PUBLICO, TUTOR_INTERROMPEU_TRATAMENTO, ALTA_MEDICA, CONTINUOU_TRATAMENTO,
    EUTANASIA_INDICADA, EUTANASIA, TUTOR_OPTOU_POR_EUTANASIA, PCR
}
